
workflows:
  default-workflow:
    name: Default Workflow
    max_build_duration: 10
    environment:
      vars:
        FCI_KEYSTORE_PATH: /tmp/keystore.keystore
        FCI_KEYSTORE: Encrypted(Z0FBQUFBQmp4bElEb2QybFpoTWJUWW1vNEVpNDRoTTVva1ROVTNRSlAtM01wbzhSakpoTF9LNGRIMnBGWDdrbzYyMVlpX0g2bUpZM0Z2VVZVVE9XV1lkVDhicGQ5RnNGWDJRLXBjbUZEcEVIRVduWUg1WjlPQTdFR01YaTdXcVNDVjNON2xKczRsNG5IMFA3LXVmTl9SZUNBcllQWE9vSzgxemZwTGk4NFMtN0tfbHYzWXZJV3YtekR3VE5tUmNVX1EtVW1VNFRkMEJJM20xQVdMOVpmVUotT1Bpc0N3c2xnUW15YUp4QjVOdzd2Q0tTbXFwNmZGRG8xaGcwcUppcTZmbWN2NzQxWHdmXzNHVl94UzN2WjVBZHY3WEFzV05SaE5DTnFMNXlyMHJkNXIxMnJUY3hjSGlnb3VGU0kweF96OWtvemc3cWV5aTZ0Um90UWxrV1NaVGdPSzZsUlBVQWsyN3EzWkdtaG5wcFJrVksycXBjQXRxLUdhbVhhVFl3U3Z5WGVVUDdIOUFyLVZlRjNuaUY0bVlUT1J2ME5fOS1uZ1RQSUQ0ODdlYllaNnJCX3ZyZHQ2cFlzbld4RFhYS3lhT3VaSnlsbkdrdVc2QWdyTUlqTGllaEhaTjJRNEZlVVFrNUJfY3FJTDNnUDhTaUYwZjFmamFKRllmTVV2N3JiSGhiTThVcXhiM25WMjdic0NZa1IxbXdGWklqbktLaXhwS1dPaHk0WjJ5akVzY0pkM0hsajcxUXpnd0xkeFg5d2c4cWk4d3MyTklfSjhFS1E2Szd3VHdWX0R6dmh2RDZMdjZVTUVSUkgxeDg3NndyMzBXYlhwWEtzVUNFTWFoeTZrRmpaYVVWTmZUQVVIblRvY3hHamp4SWQ1Y09JWk1fSE9sZjh4LTRhOXd4TWpHRVhUbkpPMDhKYkdaSXlPZHpLNUt3ZlFMb2FzVWZlWFRxMjExVms0N2J2MERHN1l3S01CenFBLUIwT2pzOXJ0TkFhN1htU2VuMFZwd3BrbWU5ZXdHWEdGSUtOaXdrVVkyUEVUVHpNZHZwc2Z0eTdMT3BlM3RQYjRXY0pOMFVpOWF0WW1IdHdqbUdVd2NjUnRKYUNmczd5SXJENkM5b1g3aml1N3M2NnpqbG5xRnlzOTEwdHoyYktSSEFWNzRjbVRkd2pCeTE5elJINkFXRzlRT25xcTktWmYwZkZYOFRIaGQyZG12NFRGcG1lM3pBNmF3TllaTmpGa1JtZ1RRU2JGUHNRWnQ4YlRMaDhKY0p5RURnVl9XUDBpWlBPSzhwX21rOTBTaU9mdzVHSWdCZkw0dDB1RVF1ZjZCT1d0UV9POUVuaFNTZmx6Q0RKRkNxWTdfSTV5cTc4eENQUXc1bUVtTGdreFBOQS1JQURONk50VGtxQ3dvdHpEaFpJT3R3anc2YVl0MGtqYW9mNS1jQzlScG5CdWk1TldpYjRKUTZiVkJ5TDE1cTd0TGhyVkVtd1cyVTRPR3JTd3dPNW5TUE1ZZS1TTjVfTkVpZFUtMUdiM2dnTXViUkZWeG1Rd3JoUWppbUk1cEhFOWhvejJtLVNIVlNKUlMwT1dSU0p0Q1V0eEd4eXh1ZnNzNDlYdEgxazFWODdKYW5Xand1NVp2YkMwQVZtM0ZBNUhqMGp5MzFxYklvZjYyaVlVMGFTQnJCZEQyMWh3XzdoS04wRDlyOGxEam1fYjNHOVluUERWbWVQOTEydE12Mjg3SDlRTGdhYThEN29lYjA2eVNQcUoyUFJ6SE9GTlFlV0Z6S2N6UDNPT0pXNDY2UXJpcTVZeGNzS3NCYUxfNlo0U2JoRU9qN0VHZWVlRUJNLVJ2bWhJUnhlRG1NQkFaRENMMGczNDctRWRiM2dCNnQ1WlJwanJNdS1Jemp2VklDa2hvNE05RGVMTzNQTUtsOFI3Y2tUcGpYM3JIR0NIcmRLSnBXZUJRcUV2X1NlVlc1VWp4WkY2N0FxaWg5R0N6UmJZZm5aMUdtMXhvNVNpcEY0OGtSVXNUR045Sml4cG92ZE1pY04xNlVsMno0UlQxWEY1N1Vya0hWSlpqU1NGUVBsYWtvZFR1cC03OTlabnZDcF9mVWVPNFNkay0wRlhlYUQ2VjFaQW9iejhfR0NFLVRPSi1VamtFWi1neFMzY191b2l1WWdoTW1MOGI4blBhb0NwdGJvMUtNY3RFcGJRamFSRUxxdHRyc2VMb09DYXJ4Y3pWSEJ6UGJON083X0M4a3VMUS1PTzdiRVFqaS03bF9DWHFtUlM0UF9OREFPcmtfZ2pBcWRweHhqTXdsMU55X3ZCeV9PNE8teTRjZzlxNlVUUnBKVDNlM0Rmc3RKclRFQ2hQM0xUQ3RzQ0ZfOXlHSXVYWVJOd2ZrRmU5N0J6Y2JPSllyelZkSEo0c21fWTdka19LTlRSc0ZtMWN3M3VnNld6RG1pS3RDX1dOeThZc0RJcF9FTjRTS084MlYzMU1Ja0lHdEdMbHVIZy02VkZBdzEtUGtieUdCNWF6U0pKUU5JTEZjYTVpVWRVNFFkZUtMMlAxaWU3RjhfWjZBaEJnbVE3MWtyZjBvbFRaWFdhQmp0aXVTM05iY0o4ZnhNUmJaemxhbzVxVWJmQ1ViZ3hOV2EwMWQ1V2UxaDZIWGRLdlpySG5DMGpDTjVVZG5sNmFTN2tPU3VvUGJlNWdpdFpFWTBZOGxzSUxsUmE2QWJxUTJ3aGx0MGQtWjNGd2h2UjR3LXFIMFRFT0F3cld1OURTWG5iamRyUG5MZHVsdWJ3MjhudmZQRjhxU2Uyc19GMkt3RkxnZmxlX0ptWFFYZ3VQaGJYSXNQZ0hYaW43VExhbnk2amVKZzl4c2pFUHlURmdKRjNyYjhQOV9sTjNpbDdldnk5dzZ2ZjFYQ05LSjloSDlMQW1uV1F6eFduNXpaRXJKdTdGZWZ3dXh5UTVsaUFOQTBHZlZtRUp1TUk2Q2RJdTdwaWFRakdINGFBaWRSdTY1UlkybS1rbGRGNV90U2lLZnkzV3VPOFVGbW1UWlBjVlFUT2EydEY1T3dQa1ZvcW5pVVExMERxQXFuMWxwNkxNTUpLYmYyaWUzS1RXb1JxY0J0ZGZFbC1FS0JTdnJxaWJKU3pTNER3VERIYlpUOTA2c2JaQW8zakxqdGdmcjlBVER3SlpWRTFmMzJoaVJtSm96NXI0bHdrM1Z5MHZybVM1Z29pU1RGU1pqUnBxeXpNYzZNUHFlSVN0ZWZ2LUF2VnJodFlIdTZoZjhYai1KWFpyQjZ4Xy1FREpiQmtmUHkwZExYeG9VblRsTWxSeGROMWxlYXBOZFJ1bUd4dEI3ano3c3VjUFpIbElnNkpyVTAzVlNxM1NnWVBPMi1RTUF4a214UVBmdFAxQjRRdHN4dEZBR2xSYTJIM1F2QjgtV0FJRjM4MllSenZLM1AwMzV0aUtUYUZuWTRlX3hvM0tTeWZNM3NKTkFEdUdRTVBycEtBTTVITjFodFdLaUNJWnpxdC1EdFFLbHZRWTZQbUVURzZ0MWw2c0l6YlBoVHRCYk5lZ01YaE5uQlhZemwxcWViZkZhRXl4NUhyemQ4OWtHdGNLc2J0dFNkRTBwT0d3YjItaWtNTGNjZEl6cXBaYWdfbEVRMTRNVVRJYU1OU3FrcnVUWTVkMEVWbXJSVGtTMkhOQmNodE9aemRfQi1VWGV4VnRQVG8ySDN5T2FXNks4RXlFZnZZRUxQNng0R3dYOGw4TzRucTVaZVUzMzJ0a0hILUpSS0xwNGxjQ2pnX09uMURWeEFRWmVtOEljcUVjRHBTZVZKRHd6VzR2dGFrUWFlQU9ZZFBxWFktZTdEQmJOM1RRODFKUGRmemN6ZEU0b24wUXV2Y2FtdTVYSjNlLWlVSnRkWV92NU43UG5BY2c4TGlHcTQtYWZXZ0UtTUY1dTFUVmJIbEQ0RHV1VlJDTnU2Q19fOW9xVU9VRmFRYXc4Z0MxbVpnUWF1T0NJbHBaVy1XSVlhbHhJNzhsVjlRdXJfZnhhYTZjZnFFeGhTcVZmTEZRM2xfMHBWVXp0NnhhOE03SmtDQTJUbnJSQWdLRUZqazliWTJtQ3JySlN2dG1vczRKbDZHbGNzRFl0ZGlkSG1QeXVwWmloYmdtbEM5ZXNzdWd5czRmLWQxckl5UWZjX3Y1LXZ5dnMtRENCMW80SnhPRkFlZmluM0FKR3I4Y0trelpLRHhQbzZVYnZsdWpCSkM0QjF1WjVGR3ZMaUVvVmpFTW1HcmJHeE8xV09OWWF3cl9nRl9vd2xaNzgtd2hCXzBlQVl6bFM1RTFwSkhIRS11N2RDNlBQLWJ4eHNWaFptelNRV0xyM3dVLVZQRUR6MXJ6dGNWU2QwSjFFY3dVQmh1WmpzNW1KUFVIT0E4NnJZV1l2WE9tU1MzRkQ2ZEpBN3ZER1B1X0N3OXV1QmFvX1F1WVRYbG8yR1lVUHJTVGdmZTNaRnRjN1ExN1g0ZDVKNXFJRURjdHotcUxQU3Awc3JqVXBLYU12SENYTXg4UnNORzNzZEJxUnZMa2g0bWhzZXBGaXhNVnlESFRIMy1CRkhSZ2JVYkUyZGF4QWxIUEJfNFM0VHAyamJxRTc0SDFRLWlqSnlFdVJkVGw0Nkd3aUY4NnZ2UHNrSjdoUEdEbEJUZ1dzeWdGdzN6RkZFNllkYTdla3VCdkxvVGhOLVpTb3RSTzQ1WUtmQ1BUSmFOVEdFTlNodVJoYmg5YjBET01HeW1JR0ZOMWVETFJaR0hjeW5ETWQzNXF0eUVkUkJwVURra0VkdTF1UG9ZaFFpRUwwZkI3czJXdWMtallFbG9JSEprbFNUajNzRXVGQWZWRDU0V1F6TlZ3RFBQRW5YMkp4SGRneUFfcVc2c1NzV1JBWmU4RkhMTlZha2EyaTJpQk44dmhrWTZRWTRKWDBDUnJ1Mmt1aFEzS2pnbUVjbVhLQUNIcFgzYzZyRk1OUjFBSzJ5UXE1TG5mS3AtUlZKMnVnbFp5d2J6MGh4SUhVdGRkeDF3dkJrT2taZlVFQnlpYzZsemxoSi1sZGIybjVPcms0X3NabTFNNmdYbmpUZ1ROaVFKYmVtUXB2WXQ3STFIcFE0dlc1Q2RYazFJZkNuT3B4ODAxYmZzWFJGUzY1R2NlSkNkTl9VQ3lwNTNzd0Q0MWJucmYyNkdlaXluYzduTTZyYlRiaEhfbDJhdzVITDVjaWcwMmZhdDE2VG54eGJ0TFh5d1k4amVzUXZ1dzRxekdwN08tTmFxMUZOOTI2SWJkX1pKWmZMUWpmSkJVTzNrMFNIUTJQTkVBU01QSkh4N1FkZk52MVJjeGR1am1lU3hDTlNwWHlHRzlFUkZORHBicFRKMlI2NnNSRy1iRU1Lb2tpUHdsbTdSQ0duTnQxOGtKYkI3TV9QRTlsbU9pSXZZVUw3YkRZZ1Q3NnNTUW1XRHc5OWhxRVZkOTkydkVTVTFLaWpPSnlqYzdpZDRqUQ==)
        FCI_KEYSTORE_PASSWORD: Encrypted(Z0FBQUFBQmp4bElEWHQ5aHVTRTNrUlNKVmVjc0RmY0pvQjFBS0NPYkFYZEpWSVowWkc2N1VTczZWa21rMmFEMGhqY090V0VrdVhCREhILUJmN1dscER5Y0ZxYnJscktMRGdWazB1R2pPOU9jTGVOS0hlTVVpcUk9)
        FCI_KEY_PASSWORD: Encrypted(Z0FBQUFBQmp4bElEcTNnSlRrRGtPY2t0M2djOW9pSmRRN29VZmNYZ09uUTlQc08zT2VIb2diQlZjdldfVkg4UWpyWEtoY0JINTNId1JvVWt1ZXg2OEgzOW0xY2lZc2NONVRya080SS1pX2g3WDFGNl9ZaExib289)
        FCI_KEY_ALIAS: Encrypted(Z0FBQUFBQmp4bElEMC1vOWludWJGYm1oVXVlUHdmZ216Zzdhamp1R1U0UmQzTlFtcUNOaFRzUHBrQzNuczFFaTJZSGJRX2lyMUpmczlmZElhQWNyVTRlZ04zdk4yMmVnRUE9PQ==)
      flutter: default
      xcode: latest
      cocoapods: default
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: '*'
          include: true
          source: true
      tag_patterns:
        - pattern: '*'
          include: true
    scripts:
      - |
        # set up key.properties
        echo $FCI_KEYSTORE | base64 --decode > $FCI_KEYSTORE_PATH
        cat >> "$FCI_BUILD_DIR/android/key.properties" <<EOF
        storePassword=$FCI_KEYSTORE_PASSWORD
        keyPassword=$FCI_KEY_PASSWORD
        keyAlias=$FCI_KEY_ALIAS
        storeFile=/tmp/keystore.keystore
        EOF
      - |
        # set up local properties
        echo "flutter.sdk=$HOME/programs/flutter" > "$FCI_BUILD_DIR/android/local.properties"
      - flutter packages pub get
      - flutter build appbundle --release --build-name=1.0.5 --build-number=105
      - find . -name "Podfile" -execdir pod install \;
      - flutter build ios --release --no-codesign
    artifacts:
      - build/**/outputs/apk/**/*.apk
      - build/**/outputs/bundle/**/*.aab
      - build/**/outputs/**/mapping.txt
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - '*.snap'
      - build/windows/**/*.msix
      - flutter_drive.log
    publishing:
      email:
        recipients:
          - vrkic.stipe@gmail.com
      firebase:
        firebase_token: Encrypted(Z0FBQUFBQmp4bElEd3hVRHBiQUk1UTk1b0JVUk1mYThBU3g1S01lUnV0cVd4ZnVIVU1NNnlURXBDelphWEY5bWpNUlFGUHFiUzByckVrZTBSQWlUNjNPVzdXcEZBNlZYaE0xWG5qTndKRDA0eWtETWhqWGdic0oyX2RMZkVacWZCNzQwQldOQ0ZISFE=)
        ios:
          app_id: 1:461137054936:ios:458a3f029139ef4db89bad
          groups:
            - Owner
        android:
          app_id: 1:461137054936:android:13b7babdf9741aadb89bad
          groups:
            - Owner
            - Test
          artifact_type: apk
