// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCxX4diqB-MVPRcLpeNbm99sxzkNuWr4Fc',
    appId: '1:195527583591:web:8359630c077c24fbddb1c2',
    messagingSenderId: '195527583591',
    projectId: 'basicandroidflutterapp',
    authDomain: 'basicandroidflutterapp.firebaseapp.com',
    storageBucket: 'basicandroidflutterapp.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyChajMDqZugHysyU2A65ghLmui6L31VHM4',
    appId: '1:195527583591:android:245fa2fde329ed02ddb1c2',
    messagingSenderId: '195527583591',
    projectId: 'basicandroidflutterapp',
    storageBucket: 'basicandroidflutterapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD0T18Jjdpz1JYFjFjJOgUKBEauyUdsodA',
    appId: '1:195527583591:ios:9bf531cc1d3278caddb1c2',
    messagingSenderId: '195527583591',
    projectId: 'basicandroidflutterapp',
    storageBucket: 'basicandroidflutterapp.appspot.com',
    iosClientId: '195527583591-c04smlgf84oud1424gre3djejs37k2fb.apps.googleusercontent.com',
    iosBundleId: 'com.example.basicAndroidFlutterApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD0T18Jjdpz1JYFjFjJOgUKBEauyUdsodA',
    appId: '1:195527583591:ios:9bf531cc1d3278caddb1c2',
    messagingSenderId: '195527583591',
    projectId: 'basicandroidflutterapp',
    storageBucket: 'basicandroidflutterapp.appspot.com',
    iosClientId: '195527583591-c04smlgf84oud1424gre3djejs37k2fb.apps.googleusercontent.com',
    iosBundleId: 'com.example.basicAndroidFlutterApp',
  );
}
