// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBLPufbFcRfKnXy7IXlkd9g1qRw_lhmcSg',
    appId: '1:461137054936:web:d3c3034969bdaffab89bad',
    messagingSenderId: '461137054936',
    projectId: 'basic-flutter-android-app',
    authDomain: 'basic-flutter-android-app.firebaseapp.com',
    storageBucket: 'basic-flutter-android-app.appspot.com',
    measurementId: 'G-TJWHK7LJZW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCkYrITk8eYXqRSdqecCMVfRqFp8gpC7Ho',
    appId: '1:461137054936:android:13b7babdf9741aadb89bad',
    messagingSenderId: '461137054936',
    projectId: 'basic-flutter-android-app',
    storageBucket: 'basic-flutter-android-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_xzibb025a3n45l8zi8nGBBKdDlnac7I',
    appId: '1:461137054936:ios:458a3f029139ef4db89bad',
    messagingSenderId: '461137054936',
    projectId: 'basic-flutter-android-app',
    storageBucket: 'basic-flutter-android-app.appspot.com',
    iosClientId: '461137054936-80kdp4mcnpor68mf21n8lo0ohgl6120l.apps.googleusercontent.com',
    iosBundleId: 'com.example.basicapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA_xzibb025a3n45l8zi8nGBBKdDlnac7I',
    appId: '1:461137054936:ios:458a3f029139ef4db89bad',
    messagingSenderId: '461137054936',
    projectId: 'basic-flutter-android-app',
    storageBucket: 'basic-flutter-android-app.appspot.com',
    iosClientId: '461137054936-80kdp4mcnpor68mf21n8lo0ohgl6120l.apps.googleusercontent.com',
    iosBundleId: 'com.example.basicapp',
  );
}
